github:
  username: ${{ secrets.JAVA_GITHUB_USERNAME }}
  token:    ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}

codeowners:
- path:  "*"
  owner: "@paketo-buildpacks/java-maintainers"

package:
  repositories:   ["docker.io/paketobuildpacks/azure-application-insights","gcr.io/paketo-buildpacks/azure-application-insights"]
  register:       true
  registry_token: ${ secrets.PAKETO_BOT_GITHUB_TOKEN }

docker_credentials:
- registry: gcr.io
  username: _json_key
  password: ${{ secrets.GCR_PUSH_BOT_JSON_KEY }}
- registry: docker.io
  username: ${{ secrets.PAKETO_BUILDPACKS_DOCKERHUB_USERNAME }}
  password: ${{ secrets.PAKETO_BUILDPACKS_DOCKERHUB_PASSWORD }}

dependencies:
- id:   azure-application-insights-java
  uses: docker://ghcr.io/paketo-buildpacks/actions/github-release-dependency:main
  with:
    glob:        applicationinsights-agent-.+.jar
    owner:       Microsoft
    pre_release: false
    repository:  ApplicationInsights-Java
    token:       ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
- id:   azure-application-insights-nodejs
  uses: docker://ghcr.io/paketo-buildpacks/actions/npm-dependency:main
  with:
    package:     applicationinsights
    pre_release: false
